-- Add up migration script here
BEGIN;
CREATE EXTENSION IF NOT EXISTS CITEXT;

CREATE TABLE IF NOT EXISTS users (
    id                    UUID DEFAULT uuidv7() PRIMARY KEY,
    email                 CITEXT UNIQUE NOT NULL,
    password_hash         BYTEA NOT NULL,
    display_name          TEXT,
    is_email_verified     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login_at         TIMESTAMPTZ,
    jwt_token_version     INTEGER NOT NULL DEFAULT 0,
    locked_until      TIMESTAMPTZ DEFAULT NULL,
    fail_count_since  TIMESTAMPTZ DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS refresh_token_devices (
    id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id            TEXT NOT NULL,
    current_hash         BYTEA NOT NULL,
    previous_hash        BYTEA,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_rotated_at      TIMESTAMPTZ,
    absolute_expires     TIMESTAMPTZ NOT NULL,
    revoked_at           TIMESTAMPTZ,
    user_agent           TEXT,
    ip                   INET,
    UNIQUE(user_id, device_id)
);

CREATE TABLE IF NOT EXISTS sign_in_attempts (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    target         TEXT NOT NULL,
    success        BOOLEAN NOT NULL,
    ip             INET,
    user_agent     TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Count failed attempts by IP over a time window
CREATE INDEX idx_sign_in_attempts_user_ip_fail
    ON sign_in_attempts (user_id, ip, created_at DESC)
    WHERE success = false;

-- Count failed attempts by user over a time window
CREATE INDEX idx_sign_in_attempts_target_fail
    ON sign_in_attempts (user_id, created_at DESC)
    WHERE success = false;

CREATE TABLE IF NOT EXISTS api_keys (
    id               UUID DEFAULT uuidv7() PRIMARY KEY,
    user_id          UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name             TEXT,
    key_prefix       TEXT NOT NULL,
    token_hash       BYTEA NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used_at     TIMESTAMPTZ,
    revoked_at       TIMESTAMPTZ
);


ALTER TABLE urls
    ADD COLUMN created_by UUID REFERENCES users(id) ON DELETE SET NULL,
    ADD COLUMN password_hash BYTEA,
    ADD COLUMN expires_at TIMESTAMPTZ,
    ADD COLUMN description TEXT;

ALTER TABLE aliases
    ADD COLUMN created_by UUID REFERENCES users(id) ON DELETE SET NULL,
    ADD COLUMN password_hash BYTEA,
    ADD COLUMN expires_at TIMESTAMPTZ,
    ADD COLUMN description TEXT;

COMMIT;
